AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a role with read-only permissions to EC2, EKS, RDS, Route53, and S3 services, and allow assumption by a specific AWS account with an external ID
Metadata:
  Source: https://github.com/otterize/setup/aws-metadata-integration-setup-template.yaml

Parameters:
  OtterizeAccountId:
    Type: String
    Description: The AWS account ID that can assume this role

  ExternalId:
    Type: String
    Description: An external ID to provide additional security in the role assumption

Resources:
  OtterizeMetadataIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: OtterizeMetadataCollectorRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${OtterizeAccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

Outputs:
  RoleArn:
    Description: The ARN of the read-only role
    Value: !GetAtt OtterizeMetadataIntegrationRole.Arn
    Export:
      Name: OtterizeMetadataIntegrationRoleArn
